ALTER TABLE messages ADD COLUMN IF NOT EXISTS intent TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS persona TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS context_json TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS metadata_json TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS transform_history_json TEXT;
